server:
  port: 8040
spring:
  application:
    name: user
  datasource:
    name: ordersystem
    url: jdbc:mysql://localhost:3306/ordersystem?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.monkeyhlj.entity